### ISSUE TITLE
Add promo video to website

### ISSUE THREAD

**Issue by WillieCubed** [aisutd/hackai.github.io#16]
Comet Marketing has created a promotional video for the event. It should be displayed on the website, replacing the first image (row 1, column 2 in the grid) next to "What is HackAI?".

A link to the video can be found [here](https://www.youtube.com/watch?v=CmlHXa9AKUM).

**Comment by SaminKhan35** [comment]
Completed. This change can now be viewed in "added-promo-vid" branch
