### ISSUE TITLE
Create schedule page that fetches from Google Sheets

### ISSUE THREAD

**Issue by adityarathod** [aisutd/hackai.github.io#4]
**Depends on**: Schedule information as provided by HackAI organizer team

We need to develop a good-looking, responsive schedule page that shows all the events/talks occurring during HackAI.

## Schedule Data Fetching

One key part of a schedule page is getting the actual schedule data. Here are three ways I've thought of to do this. This is not exhaustive, so if you have a better idea, let me know.

### Approach 1: Google Calendar [Build time]
One approach is to load data from an arbitrary Google Calendar at build time using [`getStaticProps()`](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation). This is a bit more work from an implementation standpoint but is superior to Approach 2.

### Approach 2: Hard-coding [Build time, not recommended]
This approach involves storing events in a TypeScript file that then gets compiled down into the finished bundle. This is harder to update because a developer has to manually make the changes, rebuild, and redeploy. For an example of this, see [this file](https://github.com/acmutd/hacktoberfest-site/blob/master/schedule-data.ts).

### Approach 3: Build API w/ Google Calendar [Dynamic, at load time]
This is a slightly more complex approach which requires us to spin up a cloud function/lambda somewhere, parse some Google Calendar stuff, and return a JSON list of events to the client. This saves on having to rebuild the site every time the organizing team makes an update to the schedule, but requires us to have some server-side code too which may get harder to manage.

## Inspiration
- [This is an event page I built.](https://hacktoberfest.acmutd.co) The schedule is designed using CSS Grid and is generated at build time. (for the source code of the Schedule component, see [this](https://github.com/acmutd/hacktoberfest-site/blob/master/components/schedule-event.tsx) and [this](https://github.com/acmutd/hacktoberfest-site/blob/master/components/schedule.tsx).
- Pretty much any [MLH member event](https://mlh.io/seasons/2021/events) has an amazing event schedule page that you can look to for inspiration.

**Comment by adityarathod** [comment]
**Approach 1** is preferred, per @WillieCubed

**Comment by WillieCubed** [comment]
Just a note, the spreadsheet we've been using to tentatively plan events can be found [here](https://docs.google.com/spreadsheets/d/1ZhVRTgYO4Xz4wOPmQ6sLYj-qzwgzeT7-PAOxdJCoTbo/edit#gid=0). The (in progress) events calendar can be found [here](https://calendar.google.com/calendar/embed?src=c_qi882c795f5uo8r0sh890e12a4%40group.calendar.google.com&ctz=America%2FChicago). I suggest you or @SaminKhan35 get started building the backend for this.

**Comment by WillieCubed** [comment]
Note that all events will have the following format:
- Event Title
- Event Location: "Online"
- Event Description
  - Description text
  - Presenter
  - Track

For the "Event Description, multiple pieces of information will be embedded in the description content. For example:

> **About:** This is a workshop or presentation about etc., etc., etc.
> **Presenters:** Name 1, Name 2
> **Track:** Track 1

**Comment by adityarathod** [comment]
An API key for Google Sheets has been created under the aisociety GCP org, meaning any dev within the org should be able to get the key. I've created a dev key for now that's pretty unrestricted in terms of where it can be used (but it _is_ limited to the Google Sheets API). I'll generate a prod key which is even more restrictive soon.

**Comment by WillieCubed** [comment]
Closing this since the welcome packet contains a schedule. We'll keep in mind the idea of populating the website using an existing data source for aisutd/org-site#24.

**Comment by adityarathod** [comment]
I just merged in a schedule.
